### ISSUE TITLE
Update Install Instructions

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/Connect-Me#16]
We changed the Project Structure and thus, the instructions became obsolete.

* Update the Steps
* Remove the image and create new images
* Add images for Firefox too.

**Comment by 0x48piraj** [comment]
Will you mind completing this @realslimshanky ? :blush:

**Comment by realslimshanky** [comment]
@0x48piraj It would be better if I allow newcomers to take this issue. I'm working on my [GSoC project](https://salsa.debian.org/new-contributor-wizard-team/new-contributor-wizard) nowdays.

**Comment by Biswajee** [comment]
@0x48piraj May I work on this issue ?

**Comment by realslimshanky** [comment]
@Biswajee please go ahead.

**Comment by Biswajee** [comment]
I have made a PR with proposed changes. Please look at it 😃

**Comment by Biswajee** [comment]
@realslimshanky I have made the requested changes and made an updated PR.

**Comment by 0x48piraj** [comment]
Merged the PR. Closing the issue.
