### ISSUE TITLE
Updating current image for 'Interactive How-To' for Chrome

### ISSUE THREAD

**Issue by Biswajee** [fossasia/Connect-Me#29]
![screenshotextension](https://user-images.githubusercontent.com/26689027/46298536-f2090100-c5bc-11e8-95bf-95995e3e6d6b.png)
Shall I open a PR to update the current 'Interactive-How To' image with this updated one ?

**Comment by saraansh1999** [comment]
I tried my hand on it.
Can you please check out PR #31

**Comment by saraansh1999** [comment]
Could you please check out the PR?
Thanks

**Comment by 0x48piraj** [comment]
Merged. Closing the issue.
