### ISSUE TITLE
Enhancing `onclick()` buttons

### ISSUE THREAD

**Issue by 0x48piraj** [fossasia/Connect-Me#3]
## Current State : 
![Click Bug](https://github.com/fossasia/Connect-Me/raw/master/assets/StarFOSSv1_Clickbug.gif)

## Expected Outcome : 

**_Direct clicking should open the link in a new tab._**

**Comment by vaibhavsingh97** [comment]
Claiming

**Comment by prshntsingh** [comment]
@0x48piraj @vaibhavsingh97  Is this issue still open?I can't see the changes reflected in my local machine.I am new to open source please help.

**Comment by 0x48piraj** [comment]
Clone and move to development branch, and then try to launch and test the application.

**Comment by prshntsingh** [comment]
@0x48piraj Can you please tell me **how to move to development branch?** I can see only one branch in my cloned repository and this repository.I am new to git please help.

Where can I communicate for doubts?Is there any chat channel dedicated to this project?

**Comment by 0x48piraj** [comment]
**Use FOSSASIA Gitter Channel - https://gitter.im/fossasia/fossasia**

**Comment by vaibhavsingh97** [comment]
As @0x48piraj Had deleted development branch so this bug is active again. @prshntsingh This is a beginner friendly bug so you can fix it

**Comment by prshntsingh** [comment]
okay @vaibhavsingh97 thank you!! :)

**Comment by 0x48piraj** [comment]
As **mariobehling** has deleted `development` branch, the fix is missing again.
@prshntsingh Just use `target` attr. in `href` to fix the bug.
Ping - @vaibhavsingh97 :+1:

**Comment by prshntsingh** [comment]
Will do it @0x48piraj 🙂
