### ISSUE TITLE
Want to work on the TODO task under Girlscript Summer of Code

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [fossasia/Connect-Me#33]
Admin, I would like to work on the project.

**Comment by 0x48piraj** [comment]
Sure. you can look around the code-base and for queries, you can message me on [Gitter](gitter.im)

**Comment by NirmalKumarJoshi** [comment]
I have been working on the todo list and fixed the issues such as -

- Added Subscribe Button.

- Added Social Links such as Facebook, LinkedIn, Twitter, GitHub.

![social and subscribe demo](https://user-images.githubusercontent.com/29129357/52859259-4539b580-3152-11e9-9a6a-04f7c671f52e.png)

The subscribe and social buttons are working. Are the changes fine? @0x48piraj 

Fixing more issues!

**Comment by NirmalKumarJoshi** [comment]
Apart from Twitter, Facebook, GitHub, LinkedIn which other social links should I add?

**Comment by 0x48piraj** [comment]
Thanks @NirmalKumarJoshi !

Closing the issue as the respective PRs have been merged/resolved.
