### ISSUE TITLE
Improve User Interface

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [fossasia/Connect-Me#35]
The look of present extension is plain and can be improved for better user experience. The extension look can be made much better by adding Bootstrap or Materialize.

Can I work on this @0x48piraj ?

**Comment by HemabhKamboj** [comment]
@0x48piraj. I also want to work on the same

**Comment by 0x48piraj** [comment]
Go for it.

**Comment by NirmalKumarJoshi** [comment]
Thanks. Working on it.

**Comment by 0x48piraj** [comment]
Similar issue exists. Closing this issue.
**[ref]** : https://github.com/fossasia/Connect-Me/issues/2
