### ISSUE TITLE
Adding other social links in firefox extension

### ISSUE THREAD

**Issue by creyente1897** [fossasia/Connect-Me#44]
**I am submitting a feature request**

**Description**
Currently there is no other social links as provided in chrome

**Expected Behaviour**
Should be having social links as that in chrome extensions

**I would like to work on this issue**

**Comment by NirmalKumarJoshi** [comment]
@creyente1897 There is already an issue referenced to it #34 and that issue is assigned, You can look for other.

**Comment by creyente1897** [comment]
@NirmalKumarJoshi  Ok :+1:
