### ISSUE TITLE
Extension Fossasia Pic margin is not set perfectly

### ISSUE THREAD

**Issue by Amanchouhan192** [fossasia/Connect-Me#54]
**I'm submitting a ...**

- [x] bug report
- [x] feature request

**Description :**

fossasia pic in the extension is not set perfectly
and adding Instagram social media handle in firefox fossasia extension
**Current behaviour:**

margine is not set in left side unequal margine
and adding Instagram social media handle in firefox fossasia extension
**Expected behaviour:**

setting the pic of fossasia equal margin distance in all sides
and there will be new social media link of instagram

**Would you like to work on the issue?**

yes

**Comment by 0x48piraj** [comment]
Staling, low priority issue. Closing.
