### ISSUE TITLE
Update README.md file adding updated links

### ISSUE THREAD

**Issue by Amanchouhan192** [fossasia/Connect-Me#56]
**I'm submitting a ...**

- [] bug report
- [x] feature request

**Description :**

Adding more links 
**Current behaviour:**
there is missing updated links

**Expected behaviour:**

More links of social media handle 

**Steps to reproduce:**

**Screenshots**

**Would you like to work on the issue?**

yes

**Comment by msknkh** [comment]
Hey! I would like to work on this issue.  But i would like to confirm what kind of links do you wish to add? Social media handles of Fossasia?

**Comment by 0x48piraj** [comment]
Closing. ref https://github.com/fossasia/Connect-Me/pull/60
