### ISSUE TITLE
Add rounded corners to all icon and pic

### ISSUE THREAD

**Issue by Amanchouhan192** [fossasia/Connect-Me#59]
**I'm submitting a ...**

- [] bug report
- [x] feature request

**Description :**

adding round corners to the icon and the fossasia pic
**Current behaviour:**

simply adding css property

**Expected behaviour:**

you can see the rounded corner icons which is attractive.

**Steps to reproduce:**
add css property

**Screenshots**

![hj](https://user-images.githubusercontent.com/25322672/54075546-c524ec80-42c6-11e9-92ad-59bca0d9ad25.jpg)

**Would you like to work on the issue?**

yes

**Comment by Alokpro1** [comment]
I want to work on this issue.🙂

**Comment by Amanchouhan192** [comment]
@Alokpro1 it's done by me due to some problem in my account not able to make a separate pull request to the project.

**Comment by arghac14** [comment]
@Amanchouhan192 Can I fix this?

**Comment by 0x48piraj** [comment]
Staling and low priority issue. Closing.
