### ISSUE TITLE
Improvement in UI 

### ISSUE THREAD

**Issue by AkashM398** [fossasia/Connect-Me#63]
**Description :**
Improving the UI design of the extension by adding few features and animations and changing the UI theme 

**Would you like to work on the issue?**
Yes 
#35

**Comment by yati1998** [comment]
Hello, I would like to work on this. Can I?

**Comment by AkashM398** [comment]
but actually I am working on this issue, anyways even you can work on this..

**Comment by 0x48piraj** [comment]
Ping @AkashM398, this issue is staling.

**Comment by AkashM398** [comment]
Will make the commit by this week

**Comment by AkashM398** [comment]
Hey @0x48piraj I have made major changes in the UI design for Chrome extension, Shall I commit the code?

**Comment by 0x48piraj** [comment]
Obviously.

**Comment by AkashM398** [comment]
@0x48piraj Could you label this issue as GSSOC19?
