### ISSUE TITLE
Add Gitter social icon

### ISSUE THREAD

**Issue by satya-vinay** [fossasia/Connect-Me#64]
**I'm submitting a ...**

- [] bug report
- [x] feature request

**Description :**
Add Gitter channel of [fossasia](https://gitter.im/fossasia/fossasia?source=orgpage) in social icons.
**Would you like to work on the issue?**
Yes

**Comment by punkstar25** [comment]
can i work on this issue...

**Comment by punkstar25** [comment]
if am correct the task is to add social icon of gitter channel of fossasia in the Releases/firefox/icon file...
plz correct if  i'm wrong... it is my first contributation in open source

**Comment by satya-vinay** [comment]
@punkstar25 sorry I didn't see your comment. but I know a small change where you can contribute.
Soon after this merge I will raise an issue and notify you.

**Comment by punkstar25** [comment]
ok,,,is my point is correct or not i.e. add icon  in Release/firefox/icon file ???

**Comment by satya-vinay** [comment]
@punkstar25 ya and some additional changes like resizing of pop up window size after adding gitter icon.
